### ISSUE TITLE
Question about GSA

### ISSUE THREAD

**Issue by codlife** [TalkingData/Fregata#10]
HI @xiongxie @hierarch devs:
 I have see your papers about Greedy Step Averaging: A parameter-free SGD method, In algorithm 2, I just see you use line search to get step size , why don't we get step size like algorithm? Can you give me a example in which case, we will use line search? thank you!

**Comment by MarcusYF** [comment]
Hi,
In fact, instead of performing line search literally in GSA, we use the approximation formula to compute step size. The line search is conducted by hand in the derivation of the formula. Maybe it's kind of misleading that we use the term line search in algorithm box. @codlife

**Comment by codlife** [comment]
thank you @MarcusYF ,Besides In your paper's part 3.2,it's better to  use w instead of beta.
