### ISSUE TITLE
Question about RDT

### ISSUE THREAD

**Issue by patrickchense** [TalkingData/Fregata#11]
Hi 
The RDT code example is not working with 0.0.2, 
1. new RDT(numTrees: Int, depth: Int, numFeatures: Int) only support 3 args
2. rdt.train(Array)  accept an array not SparseVector 
3. where is method asNum in : (l, asNum(c), ps(l.toInt))
4. how to save model
5. how to find out what accuracy on each label , that's say I have two(0/1).

Please help

**Comment by bjuthjliu** [comment]
Hi
for Question 1
The class RDT in version 0.0.2 is a parent Class, and the RDTClassification and RDTRegression extend from it.
If you want to make a prediction, then "TestClassification.scala" can be referred.
for Question 2
When training a model, we need an Array representing the training datas, and the elements of the Array is SparseVector representing the instance, so we need rdt.train(Array(SparseVector))

**Comment by patrickchense** [comment]
thanks bjuthjliu
what about Q4 and Q5

**Comment by bjuthjliu** [comment]
for Q4,  all the models in Fregata extend from Serializable, so we can read/write models through Serializable's API.
for Q5, the Confusion Matrix will be published in later version.
