### ISSUE TITLE
Is there something wrong with the calculation of greedy step size in softmax codes?

### ISSUE THREAD

**Issue by qf6101** [TalkingData/Fregata#13]
I notice the calculation of greedy step size in [softmax codes](https://github.com/TalkingData/Fregata/blob/master/core/src/main/scala/fregata/model/classification/SoftMax.scala#L47) is inconsistent with the paper's representation.

I.e., the variable 'probs(yi)' is not equal to 'b_k' of equation(10). Did you miss applying an exponential function to it? The same problem happens to the variable 'product'.

**Comment by takun2s** [comment]
yes, the code is missing exponential function .But not affect the effect more .
I will fix it .
Thanks very much !
