### ISSUE TITLE
A question about SparkTrainer

### ISSUE THREAD

**Issue by jinxin0924** [TalkingData/Fregata#16]
I have a question about `trainer.ps.set(ws)` at the end of the function "run" in SparkTrainer.scala. If we use ps.set() rather than ps.adjust, the  epochNum is meaningless. Do I understand the code correctly?

**Comment by takun2s** [comment]
1. The local model in every partition , adjust the weights , than average the weights , and set to ps , the next epoch will broadcast the weights .
2. There is 2 epoch num 
  - epochNum is the epoch for spark, every epoch will broadcast weights , train local model and average weights .
  - localEpochNum is the local model training epoch in every partition .

**Comment by jinxin0924** [comment]
Many thanks. I think it's kind of like Random Forests, right? Each partition trains part of data, and then average the weights.
 I can understand that your algorithm can have less time cost than mllib ( I have read your paper. GSA is quite good), but I do not know why it can train 1 billion X 1 billion data set. You do not split the data by rows, so each partition will train a mode using the data with 1 billion features...Is it possible?
@takun2s

**Comment by takun2s** [comment]
Yes , each partition trains part of data .
The current version , you'd better not to train the feature more than 100 millions . The treeReduce is the bottle neck of the memory .
We have a inner version support 1000 billion features , and have not open source .
