### ISSUE TITLE
I get a model result with all Wi = NaN

### ISSUE THREAD

**Issue by makailove123** [TalkingData/Fregata#17]
I trained a model with 2500000 samples and 900 features. But the result Wi were all NaN. I randomly chose 1000 samples from the dataset, and the reault seems ok.
Does it have limitation on the size of dataset or feature values?

**Comment by takun2s** [comment]
No, there is no limitation of the data size .
You could try to normalize the data .

**Comment by qf6101** [comment]
I encountered a similar overflow problem with [SoftMax](https://github.com/TalkingData/Fregata/blob/master/core/src/main/scala/fregata/model/classification/SoftMax.scala#L108). And I fix the code as follows.

    val margins = ws.map { w =>
      VectorUtil.wxpb(w,x,1d)
    }
    val maxMargin = margins.max
    val adjustedMargins = margins.map { margin =>
      margin - maxMargin
    }
    val mes = adjustedMargins.map {...
