### ISSUE TITLE
Is there a way to dump or export model weights?

### ISSUE THREAD

**Issue by robbine** [TalkingData/Fregata#8]
Is there a way to dump or export model weights?

**Comment by takun2s** [comment]
you can get weights like this , for logistic regression
val model = LogisticRegression.run(trainData)
    val localModel = model.model
    val weights = localModel.weights

**Comment by takun2s** [comment]
Sorry,I checked current version code , can't get weights . It will support next version .

**Comment by kiminh** [comment]
Thx, when will you release the supported version. Or I have to pull the parameters.

**Comment by takun2s** [comment]
We released 0.0.2 yesterday, it can get the weights .

**Comment by kiminh** [comment]
that's just awesome. Thx a lot

**Comment by kiminh** [comment]
hi,I want to know the bias of lr model is weights(weights.size-1),is it right? In my case,the bias turns out to be 0.0. I'm confused in which case the bias would be zero.

**Comment by takun2s** [comment]
I checked the code , it is a bug ,it doesn't update the intercept weight . We will fix as soon as possible . 
Thanks .

**Comment by takun2s** [comment]
@kiminh  the intercept bug fixed . 
thanks .
